### ISSUE TITLE
missing board outline layer 

### ISSUE THREAD

**Issue by 122christo** [anabrid/the-analog-thing#1]
Hi,
thank you for this amazing project!
I've tried to upload your Gerber files to AISLER, but they found an issue:
They need a board outline file and a special formated drill file
"Important:

    Make sure your drill files are exported in 2:4 precision and are set to the unit inches.
    Please ensure that the board outline layer only contains the board outline
...
Please name your files like the following:
...
Board Outline | project_name.boardoutline.ger"

Please can you upload a board outline layer?
Thank You
Chris

**Comment by kdahlmann** [comment]
Hi Chris, 

there are 2 new zip archives uploaded with separated board outline layer. Please use this complete new archive as some drill holes have been removed from board outline to drills (or you will miss them). If your manufacturer wants specific file names, you have to rename them by yourself. The precision is higher with 3:5 and of course in inches (not metric). This resolution is standard for manufacturers and in my eyes the 2:4 precision is just the minimum. 

We never had problems with manufacturing companies with our production data and if this company is not able to use them, you may consider to use another supplier. Please keep also in mind, that the BASE is standard 1.6mm with HAL (hot air leveling) while the FRONT is double thickness with 3.0 or 3.2mm and ENIG (gold).

Best regards,

Karl

**Comment by 122christo** [comment]
Thank You!
